language: ruby
rvm:
- 2.1.1
bundler_args: --without kitchen_vagrant
before_install:
- echo -n $EC2_SSH_KEY_CHUNK_{0..25} >> ~/.ssh/id_ec2.base64
- cat ~/.ssh/id_ec2.base64 | tr -d ' ' | base64 --decode > ~/.ssh/id_ec2
- gem install bundler --pre
script:
- bundle exec rake travis
after_script:
- bundle exec kitchen destroy
env:
  global:
  - EC2_SSH_KEY_PATH="$HOME/.ssh/id_ec2"
  - KITCHEN_YAML=.kitchen.cloud.yml
  - secure: h/tnUCXjjMBR1frPIPKFjqwh8LwFTw4nU7lkrT6tIrE6KPqUd0/i730BMNQuOGzbZJFNSXJkwQ73/Jx99x+bJf176aibCZpehunFDxqUUvekUgd86k0Ih00AsGGDVOM1toIdGKYkif0KXywhWA0w7BSUS07kVZ94YT4kD89ksvw=
  - secure: XuEcU7p0eFtIo8APel20awOR/cgLCxXGDnypglzeYIPvxMTOl8zV/ZSbeiy66UF8Nj8rOdHGrQ4RN1wHOKZ5TlfqTnobfML0FQ/ytXawoTTOp7EOWG4e/ltaZP+OxX7EY58JToPZV4X4O/Z8ev9qZ/S2mOp048dHim4D0ypBkVs=
  - secure: Bu4lCddykoSzLjbizQ1aLPRbychIb+7kILKY4A5l8thNlJnFK5NhUNuGISFg8KBGE9XW4JUUgztnnTbjJMa0SB31sVOeUMuW2ck+0nq+EdSBEHQ0lGB6xLcp2zFNp6Iy8DkTnoQ9cFDziWKa6lgRKEc17ErVn4DnhmmY3ByPnaI=
  - secure: CCo+fkPGY8+G+Afqs4b+JWST5bYsDaXw5O4+F7pPsIw8cdm2WOlaGH6ZaDP1QWkeZVdkEATOUBzksG6SZFr0GnZv47IDva8G+zWcCQQb4AwxxvjD/jz6lqqkt16gbByjdqrjXaP/F+xNftrwZbSpT0YlCKai6L1qxqqkNld2xEc=
  - secure: elRbmgvNdi55E9Clw0fxB15YNmc9u8LgdijnsfVTG7mLeyvUBfLRp86OmA0F1mLS2CuxfTG9ue8ZnfpO4vM9opwxBuIQsZVLUSK3o6u/Hsg5ou/0/2Ieqtm/RYC1egboAiLWSvF3xJfh/+WGv4ydoz3ofG0v8al62ihtgt1OUkM=
  - secure: DqBFHNPtVz+5iQSMz3pB8y4sn8q+GuisoaIgPmBYXlltP1tAwRc45dL8wnVDHY2VhWmqhV8qcLY2BYUpAMvAEbk9BOHBubNV4jKhEcm6V53sjUKZvIOIIlATABWlYUY3MuNA2UqTCjSlMGcLaAOJbD52c9hUp5vo4lrQFtCqf5Q=
  - secure: FG+MWAlrCJiLIO2omvl1Fr3195aXaM47fQe7S5P5hwtvyy68R9jYaLmu4W76aDM0oQcXxH1rZu9OrA4hCbOx/Y/G45tRNyhJ8wR3lEQBzPmjZ0DWe8sgu+DhrRfNvc4BIv5PzoO++WTSl8RCKWnEVXjAasEx9cir3ywpehjTQRs=
  - secure: Huua0becWj5ZcIcY6pb3JY5rkgMX1pxPdbIWmZwtCf/kKL+TgKOZQrxNKkQP9hjdwaUOgoRUkRakMvVuuJN6P18uffR26RkzGLj7tUHB9fwELGjr2a+GDo9vOjS1Z7dKUUHs+hswio/SpeaUpXYnD+8RI3d0uRzuxMTYehBp2G4=
  - secure: gtJ7DIXM94Ql4UKHeEbEIm9moXUAMzN+HusXqI3R1b9TFhSesWHVDtARrDvofGntz1wX0hWY1IzbiLa92LqFmeIW/aJmtiRRgQxI9BJNMgCv7AtX9V3habXXJbw49YyFksQF/vBErEMMHvsL46i0ZOYwxGLpAbsU8V1SnWxaXcA=
  - secure: kDwi36SR3yiIBooJww3JfmXDcgsi40L3PAZkO6VYpc6rC5VsbjrCea3ItOZTotdxThcKc33nC6orKQwd8Akpi72tZUFIleWFSU/AvYlnPyRKri6gK8C7eokE7oSU4lznlwH+iWlvZYYDrEfS3uVAPmbJUCMMxInGr3/B8rWbsKc=
  - secure: X7aFAdG76L27X62/yJC2aGWtu1wVWpNpedajOZq7JeOYc/UiXOf8YYGsjIDFD/d5zBah50PoOROnriVIVxdR2FyHOik9IyEY3VuaQOf5+vzO6nIOpLGsoPpPpvNnvdr98A9lXySdPWOdJJWH4VErl391qY19ngLaJfoOdgNFz04=
  - secure: iZRedmq/dp0ZJYJS4zzVXPVTr58Lnv7+8Wz9TzPLartQBK5YmDWz2NwEOEXsyJaJtgfRV0JWPsfXbtSlMgYmEunz+SAWZZAWPU9+iJGdV0Eb2lYnIznJa8WTP7lll0n8nfMfNOXi6B1RivgcO0hvGGsa3cwSiNg4ymGw9qOJtrs=
  - secure: CMWZK6rlGTP/0sPBvh1zwQf1oSTGjs5ZWN7CcC2SzMA5Woz3Pr0oKzX49VX/u6nz7V0yv1u33cDK6WbbaDcGwojlog3DUARxjDRA4LAA4z1GMdH6F6JVPiaJU/bqFx5gi4xqi3B+XAmh9WJw0fs66uTxlAW1wwHs2HAWi4A6ndY=
  - secure: XiUef49PVoRlqhlYRSCzotWCE8O4j5qZ26ZrojA3KKgzQCWiVVeALTEP67gxAH90ZYtqEQQUfjvRpKlgCGWxacSGY7Drt0TmbvokfPEK40/ZbIGvGm6sdx4FjGvqFmMRJHQZlsRZRyM2y9viDGTrUq725W9oFjXBl6+obF1z5VQ=
  - secure: Ii68tBy+Hnnwz/rT133ZQakmmXeW1ZSTTYtX5yqW/VX/uSY2AWRFON0R8DfN72z+x8visip2a2bWqRLv2a5LpzOkvcgAq9k8/qpJTJil26ZDkoZAgUOZCb5fkmGzONiWMHy8lraqDCkDBdGoPYyjdVxjhXKGBs3Rr9BAkyMC5iQ=
  - secure: CiJHwo/Wt7oUFNHC+S5ttrOLUx8pvAeYh7eabkO9cRoDfOSBGBE4rnBnrQHoCpyNYuLtc0ZkepSJReYG24lLlaZtv9eYoLvPgoHig1X3ff1GgJq5CoeC7QkctWTAczSyaidPc0i+HeM8CzyDSxWtMStbu7pYssGefgqynsRsls0=
  - secure: de1G4ez0pC2whifu1BRYGIpjqCniC3xzkhOl3a9+H6cVIHApEzDBI4NAoFjpwiI5ibiPqlsPTkxFYPg2JmN2KLz/ki0o3tdmpOySeLQ2y3NI5FlYyU/QacqDveH4GbmeOSRnbwzncT1uzMqQQSr7mOtMUa32JPY38O46Q5k0TC8=
  - secure: arOZquSfw6UL+SrYKGQKeBMJP8OWOEZTfgLAXlMMko0ur3DvwpLnRKdJ6uvK3k6WGvuHfmMd/RFerV3V95fUPledcUJM/B+IuniKzigVVrVdddkbDze14witzGoXJMZpeaq+csqq16nN405acf2q0VqArwdp6Cu8n57a9UmGQJY=
  - secure: lzjXrsmhhvlTPhUm1olP7f8y6sGnpyaQNBO4xHl0QMoZu9tWrzxc75Bdu6hKSsovq8FXA6yw8OeQLV5ZiaMBnUXZOwci2IxDECqkmTyEcOo0WMWv+w3l7f41ghyNRko0H46DZlIW40e1xd//GsqifWNjcs6y3NDqDn9J0ELUzxA=
  - secure: Wzu5jXwE6xrxx7s4JcH74DDd0GlOFT61gtPuZigOZwW7In1wjTbTiq6yozlgvMJXVt1Aoq+YRNA0KlXyGNDWW6BgKx/O2/7ZPiC4Kn3VsfxWwMvsx9vxLB9xDDveDf4IWokt5aj+3Vvqw8+85C2t7p76bAQMuZE8692Y6OCci98=
  - secure: ghuR7vt+VB3fMb48PhwVBVNu2q1kaTGvM2bNu7we10LroAHHA2HRnwnDNSpDhCo79TqwiTrvhk8uYIHop28gS4jPl9iqyk+dM+/SIE86Bvyg9nbQJOV60/u4PrwcJ6czxaztXUbzH4qpIn29NZ5BXHvMmGMPn+kSsVpkm0hOdA8=
  - secure: I31miPjiMMX7O+Bv8pwhdeV4ovEvJwCdoGzCxRoSfWrs5fIGOVuiTxuYj2XKj+ZVlSQeWYl02mr1t4lKubXSl7rRQ1mWt89cu91doo43X2149CBAX4rntC4gKjtenm502Evobm1IdIWUbFv7Hc3NHbjziLZsirInV2v9wdR5EGA=
  - secure: YdKnSjsE4s6Y1xdogxUUyaz3UsY3YWGXK0UMDvM+2atC7lLKdb5qJfsITc8Wajg9UIdv3RBfveB6PO2HQD++lJD6ONCaj0pI3dDe5JppKUqdXshHB3q2yCfQtuYbnq/A34O2empCUU0qUmcC5MmzlctLbm6V/q4TOQfQnb0yEvo=
  - secure: jBOmEZdw/1vm1fmtpzxEwo08F6IpbqsKaSHyUZZUh2gOE4uiJoVvAfK353oP0BBc7B6VLfwVTyKYW1kB5baUc2YxmK/VhDkWNN8s5OEWRiNaL1C4xwFK2CvSODjxkoyVTuCzxRB6KVe3ebws9rLxWRu3Zuz54xeWkkOn+Aa2Xp4=
  - secure: Aw+aEwUE94bGbcB+9dKBO5e0tPGmzHAURKkZ+QRAw6NAlmX2C6XeWJnn2R47KEyFnRJZg5Gfx2NgTrc+SA3hImBNsoKdk8FhpV9XOtYB1zZpewfHU4wxIBiCt19nPHSD2Vmk8aNRXvE5CzBud83QvYdt5hKRFuYvNYhJr6wHgbE=
  - secure: jcIJ/HyQB2mFB/31o0X5Db7/KlGJVw8PIYYMfwzJLKAk+pbiR1xmoV1AJ9QGp1z/JNpMBClNsRNnHIviaWrurrsrQyvgim3GQLb3BzQ2Z+E4+I1ZVPrrJQfYkjzrHoDcq+TvdIhd875igCh2dzP1G4txQuszES/thsO4fPpdJlQ=
  - secure: JjiozSlH7Nh14QwS1NdK9CAhxsv4BFG9P2PtysZu+wN+WhyLbdRWoio/fKGJwkyq1VrUlzFaPIwbdxdXtgFbK1AEvs6h8yrTV0o2AL+zfdQtaHDQgbJme/NcUmxOiEpUgVfOrDfrV5IubTlntzFvVaQEfoHIoTwsJRxZlT1upA4=
  - secure: U1X/Jgoo4VDaXPhLE8wzj13gPyRFnQSrP4KhmekXnN7n7EowZwr25ixWjNCHcp0bcAhlJaMg8WbNYMM6pYchZUYelZNZuU1LkNFxn1uCJ7+yaj6Q0Us9cktmm55hVZsqnxp7xGmY09H7NPy/CYanHCbeDzo395W2xR+a3ZoU9zc=
  - secure: APXnvqzAYTAEyS6GjHRmfuYiKnPO0WmUsPOEHMZ5kLuQmJi3ofwkjTKjF3zvMGkT1TjIaZk5B2BB7V7RJk5RlOn75lL5H16TF3uC7zwZSHzMDcyDSMdg90BKphSfBSqv3IeCIo3xFAh50ID+n9goXBSGXak4web8nsFaGB+MGi8=
  - secure: YTC9MjhM/wfxQPLdpYwYhA9ywaLKU+7edzPEHH7SIPKyLl2VsBh2Znt8i4SeZX4V/skCd30Ck3rLB3qajuYA//nFXUBmsRSrmnkTSvJC2jPu8OzfHMbI9eunXJ7CQc1yB2Yf30D+dsDoe3Dudf3c3j/yjKOoEN8UZas94YnMM3g=
  - secure: LqnThZvfQGTubaRmVjtwgVk8uddyKnhdW7z94InalMEWBhxE3lHXWC5ehKE6Vf7EC88pD7QZusmq7FTWv+uxePTK3BC97pxEWxNp21mUxvRnT3H2OBVbBk4NUPw5kPhPDiL2Vzqy60XWijLAlaz3BMVYyh3Cufbs+bzWvgnGGDM=
  matrix:
  - KITCHEN_INSTANCE="default-ubuntu-1204"
notifications:
  email:
  - techops@americanhonors.org
